# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroMateriais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco', models.IntegerField(default=0)),
                ('numeronf', models.IntegerField(default=0)),
            ],
        ),
    ]
